// 계정 생성
CREATE USER SCOTT_05 identified by tiger default TABLESPACE users;

// 권한부여
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SESSION TO SCOTT_05;

// 계정 삭제
DROP USER SCOTT_05 cascade;

// 계정 조회
SELECT * FROM ALL_USERS WHERE USERNAME LIKE '%SCOTT%';

// USER테이블
CREATE TABLE USERS (
  USER_ID     VARCHAR2(50)   NOT NULL,
  USERNAME    VARCHAR2(100)  NOT NULL,
  PASSWORD    VARCHAR2(100)  NOT NULL,
  EMAIL       VARCHAR2(200),
  BIRTH_DATE  DATE,
  CREATED_AT  TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT  TIMESTAMP,

  CONSTRAINT USERS_PK PRIMARY KEY (USER_ID)
);

CREATE TABLE CUSTOMERS (
  CUSTOMER_ID      VARCHAR2(50)   NOT NULL,
  USER_ID          VARCHAR2(50)   NOT NULL,
  NAME             VARCHAR2(100)  NOT NULL,
  GRADE            VARCHAR2(20)   NOT NULL,
  TOTAL_ORDER      NUMBER(10)     DEFAULT 0,
  LAST_ORDER_DATE  TIMESTAMP,

  CONSTRAINT CUSTOMERS_PK PRIMARY KEY (CUSTOMER_ID),
  CONSTRAINT FK_CUSTOMER_USER
    FOREIGN KEY (USER_ID)
    REFERENCES USERS (USER_ID)
    ON DELETE CASCADE
);

CREATE TABLE WINES (
  WINE_NUMBER     VARCHAR2(50)   NOT NULL,
  WINE_NAME       VARCHAR2(100),
  WINE_PRICE      NUMBER(10),
  REGION          VARCHAR2(50),
  COUNTRY         VARCHAR2(50),
  WINE_STRENGTH   VARCHAR2(20),

  CONSTRAINT WINES_PK PRIMARY KEY (WINE_NUMBER)
);

CREATE TABLE ORDERS (
  ORDER_ID        VARCHAR2(50)   NOT NULL,
  CUSTOMER_ID     VARCHAR2(50),
  WINE_NUMBER     VARCHAR2(50),
  ORDER_DATE      TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
  PRODUCT_PRICE   NUMBER(10),
  DISCOUNT        CHAR(1)        CHECK (DISCOUNT IN ('Y','N')),

  CONSTRAINT ORDERS_PK PRIMARY KEY (ORDER_ID),
  CONSTRAINT FK_ORDER_CUSTOMER
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMERS (CUSTOMER_ID)
    ON DELETE SET NULL,
  CONSTRAINT FK_ORDER_WINE
    FOREIGN KEY (WINE_NUMBER)
    REFERENCES WINES (WINE_NUMBER)
);

// CUSTOMER테이블에 고객 정보가 삭제되더라고 ORDER테이블에 CUSTOMER_ID 유지되도록
// 먼저 기존 제약조건 삭제
ALTER TABLE ORDERS DROP CONSTRAINT FK_ORDER_CUSTOMER;

// 다시 제약사항 추가
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDER_CUSTOMER
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID);

SELECT * FROM user_constraints WHERE TABLE_NAME = 'ORDERS';

// 주의 : DDL은 AUTO COMMIT이다.
DROP TABLE ORDERS;
DROP TABLE WINES;
DROP TABLE CUSTOMERS;
DROP TABLE USERS;


// 와인 정보
INSERT ALL
  INTO Wines (wine_number, wine_name, wine_price, region, country, wine_strength) VALUES ('FR001','Bordeaux Red',35,'BORDEAUX','FRANCE','13%')
  INTO Wines (wine_number, wine_name, wine_price, region, country, wine_strength) VALUES ('FR002','Burgundy Pinot Noir',45,'BURGUNDY','FRANCE','13%')
  INTO Wines VALUES ('FR003','Champagne Brut',55,'CHAMPAGNE','FRANCE','12%')
  INTO Wines VALUES ('FR004','Loire Sauvignon',25,'LOIRE','FRANCE','12.5%')
  INTO Wines VALUES ('FR005','Alsace Riesling',30,'ALSACE','FRANCE','13%')
  INTO Wines VALUES ('FR006','Côtes du Rhône',28,'RHONE','FRANCE','13.5%')
  INTO Wines VALUES ('FR007','Provence Rosé',22,'PROVENCE','FRANCE','12%')
  INTO Wines VALUES ('FR008','Beaujolais Nouveau',23,'BEAUJOLAIS','FRANCE','12%')
  INTO Wines VALUES ('FR009','Chablis Chardonnay',40,'BURGUNDY','FRANCE','12.5%')
  INTO Wines VALUES ('FR010','Sauternes Sweet',60,'BORDEAUX','FRANCE','13%')

  INTO Wines VALUES ('US001','Napa Valley Cabernet',50,'NAPA','USA','14%')
  INTO Wines VALUES ('US002','Sonoma Chardonnay',45,'SONOMA','USA','13.5%')
  INTO Wines VALUES ('US003','Willamette Valley Pinot',48,'WILLAMETTE','USA','13%')
  INTO Wines VALUES ('US004','Washington Merlot',38,'WASHINGTON','USA','13.5%')
  INTO Wines VALUES ('US005','Oregon Riesling',30,'OREGON','USA','12%')
  INTO Wines VALUES ('US006','California Zinfandel',35,'CALIFORNIA','USA','14%')
  INTO Wines VALUES ('US007','New York Finger Lakes',32,'FINGERLAKES','USA','12.5%')
  INTO Wines VALUES ('US008','Texas Hill Country',28,'TEXAS','USA','13%')
  INTO Wines VALUES ('US009','Washington Syrah',40,'WASHINGTON','USA','14%')
  INTO Wines VALUES ('US010','Argentina Malbec',25,'MENDOZA','ARGENTINA','13%')

  INTO Wines VALUES ('CH001','Swiss Pinot Noir',45,'GRAUBUENDEN','SWITZERLAND','13%')
  INTO Wines VALUES ('CH002','Swiss Chasselas',30,'VALAIS','SWITZERLAND','12%')
  INTO Wines VALUES ('CH003','Swiss Merlot',40,'TICINO','SWITZERLAND','13%')
  INTO Wines VALUES ('CH004','Swiss Heida',35,'VAUD','SWITZERLAND','12.5%')
  INTO Wines VALUES ('CH005','Swiss Gamay',28,'GENEVA','SWITZERLAND','12%')
  INTO Wines VALUES ('CH006','Swiss Cornalin',38,'VALAIS','SWITZERLAND','13%')
  INTO Wines VALUES ('CH007','Swiss Humagne Rouge',42,'VALAIS','SWITZERLAND','13%')
  INTO Wines VALUES ('CH008','Swiss Petite Arvine',36,'VAUD','SWITZERLAND','12%')
  INTO Wines VALUES ('CH009','Swiss Amigne',34,'VALAIS','SWITZERLAND','12%')
  INTO Wines VALUES ('CH010','Swiss Pinot Gris',29,'GENEVA','SWITZERLAND','12.5%')

  INTO Wines VALUES ('AR001','Mendoza Reserve Malbec',27,'MENDOZA','ARGENTINA','14%')
  INTO Wines VALUES ('AR002','Patagonia Pinot Noir',33,'PATAGONIA','ARGENTINA','13%')
  INTO Wines VALUES ('CL001','Chile Carmenère',24,'CENTRAL_VALLEY','CHILE','13%')
  INTO Wines VALUES ('CL002','Chile Sauvignon Blanc',22,'LIMARI_VALLEY','CHILE','12%')
  INTO Wines VALUES ('AU001','Barossa Valley Shiraz',50,'BAROSSA','AUSTRALIA','14%')
  INTO Wines VALUES ('AU002','Margaret River Chardonnay',48,'MARGARET_RIVER','AUSTRALIA','13.5%')
  INTO Wines VALUES ('ZA001','South African Pinotage',25,'WESTERN_CAPE','SOUTH_AFRICA','13%')
  INTO Wines VALUES ('DE001','German Riesling',30,'RHEINGAU','GERMANY','12%')
  INTO Wines VALUES ('IT001','Tuscany Chianti',35,'TUSCANY','ITALY','13%')
  INTO Wines VALUES ('ES001','Rioja Crianza',28,'RIOJA','SPAIN','13%')

  INTO Wines VALUES ('ES002','Sherry Fino',33,'JEREZ','SPAIN','15%')
  INTO Wines VALUES ('PT001','Douro Port',40,'DOURO','PORTUGAL','20%')
  INTO Wines VALUES ('GR001','Greek Assyrtiko',32,'SANTORINI','GREECE','13%')
  INTO Wines VALUES ('AT001','Austrian Grüner Veltliner',30,'WACHAU','AUSTRIA','12%')
  INTO Wines VALUES ('CA001','Canadian Icewine',55,'NIAGARA','CANADA','10%')
  INTO Wines VALUES ('NZ001','Marlborough Sauvignon',34,'MARLBOROUGH','NEW_ZEALAND','12.5%')
  INTO Wines VALUES ('HU001','Hungarian Tokaji',38,'TOKAJI','HUNGARY','11%')
  INTO Wines VALUES ('BR001','Brazilian Sparkling',22,'RIO_GRANDE','BRAZIL','11.5%')
  INTO Wines VALUES ('JP001','Japanese Koshu',40,'YAMANASHI','JAPAN','12%')
  INTO Wines VALUES ('CN001','Chinese Cabernet',30,'SHANXI','CHINA','13.5%')
SELECT * FROM DUAL;


SELECT COUNT(*) AS cnt, MAX(ROLE) AS role, MAX(USERNAME) AS NAME FROM USERS WHERE USER_ID = 'lch3067' AND PASSWORD = 'lch3067';

ALTER TABLE USERS ADD ROLE VARCHAR2(20) DEFAULT  'USERS';

UPDATE USERS SET ROLE = 'admin' WHERE USER_ID = 'lch3067';

ALTER TABLE CUSTOMERS DROP Column TOTAL_ORDER;

ALTER TABLE CUSTOMERS DROP Column LAST_ORDER_DATE;

ALTER TABLE CUSTOMERS MODIFY GRADE DEFAULT 'STANDARD';